name: Brew Info

on: [push]

env:
  TZ: "UTC"
  NCPU: "2"
  CI: "ON"
#  HOMEBREW_DEVELOPER: "ON"
  DOC: "gh-pages/README.md"

jobs:

  Get-brew-info:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Checkout Pages
        uses: actions/checkout@v2
        with:
          ref: "gh-pages"
          path: "gh-pages"
      - name: Get brew configuration
        shell: bash
        run: |
          . helper-fns.sh
          type -a code
          type -a twocol
          type -a h
          mount
          df -h
          env | grep -E -i 'te?mp' || true
          env | grep -i 'scratch' || true
          env | grep -i brew || true
          h 3 'General configuration information'
          time brew info 2>&1 >> $DOC || true
          time h 4 '`brew config`'
          twocol
          brew config 2>&1 | sed 's/: / :| /' >> $DOC
          brew --repo 2>&1 | sed 's/^/ HOMEBREW_REPO :| /' >> $DOC
          brew --cellar 2>&1 | sed 's/^/ HOMEBREW_CELLAR :| /' >> $DOC
          brew --cache 2>&1 | sed 's/^/ HOMEBREW_CACHE :| /' >> $DOC
          h 4 '`brew doctor`'
          time brew doctor | code || true
          h 4 'Variables set in environment'
          twocol
          env | grep BREW | sed 's/=/ :| /' >> $DOC || true
          h 4 'Variables brew sets during install from source'
          twocol
          brew --env 2>&1 | sed 's/: / :|/' >> $DOC
          h 3 'Installed taps'
          time brew tap-info --installed | code || true
          h 3 'Installed packages'
          h 4 'homebrew-core'
          time brew list --versions 2>&1 | to_list || true
          h 4 'homebrew-cask'
          time brew cask list --versions 2>&1 | to_list || true
      - name: Dump on error
        if: always()
        run: cat gh-pages/README.md
      - name: Dump bundle
        run: |
          brew tap homebrew/bundle || true
          brew bundle dump --force --describe --file=GHA-default-Brewfile.txt || true
      - name: Upload Brefile
        uses: actions/upload-artifact@v1
        with:
          name: GHA-Brewfile
          path: ./GHA-default-Brewfile.txt
      - name: Publish Data
        run: |
          cd gh-pages
          git status || true
          git diff || true
          git add -u
          git commit -m "Auto update from GH Actions"
          git push origin gh-pages
