name: Brew Info

on: [push]

env:
  TZ: "UTC"
  NCPU: "2"
  CI: "ON"
#  HOMEBREW_DEVELOPER: "ON"
  DOC: "gh-pages/README.md"

jobs:

  Get-brew-info:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Checkout Pages
        uses: actions/checkout@v2
        with:
          ref: "gh-pages"
          path: "gh-pages"
      - name: Get brew configuration
        run: |
          export nl='echo "" >> gh-pages/README.md'
#          export code='echo "\`\`\`" >> gh-pages/README.md'
          export twocol='echo " --- :| ---" >> gh-pages/README.md'
          mount
          df -h
          env | grep -E -i 'te?mp' || true
          env | grep -i 'scratch' || true
          env | grep -i brew || true
          $nl
          echo "### General configuration information" >> $DOC
          $nl
          time brew info || true
          brew info 2>&1 >> $DOC || true
          $nl
          echo "#### 'brew config'" >> $DOC
          $nl
          time brew config
          $twocol
          brew config 2>&1 | sed 's/: / :| /' >> $DOC
          brew --repo 2>&1 | sed 's/^/ HOMEBREW_REPO :| /' >> $DOC
          brew --cellar 2>&1 | sed 's/^/ HOMEBREW_CELLAR :| /' >> $DOC
          brew --cache 2>&1 | sed 's/^/ HOMEBREW_CACHE :| /' >> $DOC
          $nl
          echo "#### 'brew doctor'" >> $DOC
          $nl
          $code
          time brew doctor || true
          brew doctor 2>&1 | sed '1,4d' >> $DOC || true
          $code
          $nl
          echo "#### Variables set in environment"
          $nl
          $twocol
          env | grep BREW | sed 's/=/ :| /' >> $DOC || true
          $nl
          echo "#### Variables brew sets during install from source"
          $nl
          $twocol
          brew --env 2>&1 | sed 's/: / :|/' >> $DOC
          $nl
          echo "### Installed taps" >> $DOC
          time brew tap-info --installed | tee tap-info.txt || true
          $nl
          $code
          cat tap-info.txt >> $DOC
          $code
          $nl
          echo "### Installed packages" >> $DOC
          $nl
          echo "#### homebrew-core" >> $DOC
          $nl
          time brew list --versions
          brew list --versions 2>&1 | sed 's/^/  * /' >> $DOC
          $nl
          echo "#### homebrew-cask" >> $DOC
          $nl
          time brew cask list --versions || true
          brew cask list --versions 2>&1 | sed 's/^/  * ' >> $DOC || true
          $nl
      - name: Dump on error
        if: always()
        run: cat gh-pages/README.md
      - name: Dump bundle
        run: |
          brew tap homebrew/bundle || true
          brew bundle dump --force --describe GHA-default-Brewfile.txt || true
      - name: Upload Brefile
        uses: actions/upload-artifact@v1
        with:
          name: GHA-Brewfile
          path: ./GHA-default-Brewfile.txt
      - name: Publish Data
        run: |
          cd gh-pages
          git status || true
          git diff || true
          git add -u
          git commit -m "Auto update from GH Actions"
          git push origin gh-pages
